---
- name: Install KVM on pc portable
  hosts: localhost
  become: true
  tasks:
#### Installation KVM
    - name: Update packages
      apt:
        update_cache: yes

    - name: Install KVM and dependencies
      apt:
        name:
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - virt-manager
        state: present

    - name: Add user in libvirt and kvm groups
      user:
        name: cross
        groups:
          - libvirt
          - kvm
        append: true
    
    - name: Copy qemu.conf
      copy:
        src: /home/cross/Bureau/cours_N7/s9/Projet_cloud/ansible-host-conf/kvm-config/qemu.conf
        dest: /etc/libvirt/qemu.conf
        mode: '0600'


#### Installation Terraform
    - name: Install dependencies
      apt:
        name:
          - gnupg
          - software-properties-common
        state: present

    - name: Check HashiCorp GPG key
      stat:
        path: /usr/share/keyrings/hashicorp-archive-keyring.gpg
      register: gpg_key_check

    - name: Add HashiCorp GPG key
      command: |
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor > /usr/share/keyrings/hashicorp-archive-keyring.gpg
      when: not gpg_key_check.stat.exists

    - name: Check if HashiCorp repository
      command: grep -q "^deb .*/apt.releases.hashicorp.com .* main" /etc/apt/sources.list.d/hashicorp.list
      register: repo_check
      failed_when: false
      changed_when: repo_check.rc != 0

    - name: Add HashiCorp repository
      command: |
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
        https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list
      when: repo_check.rc != 0

    - name: Update apt cache after adding HashiCorp repository
      apt:
        update_cache: yes
      when: repo_check.rc != 0

    - name: Install Terraform
      apt:
        name: terraform
        state: present

    - name: Terraform autocomplete
      shell: terraform -install-autocomplete
      args:
        creates: /etc/bash_completion.d/terraform
      when: repo_check.rc != 0
      
#### Bridge creation and config

    - name: Bridge creation checked
      command: nmcli connection show br-test
      register: bridge_check
      failed_when: bridge_check.rc != 0
      changed_when: false

    - name: Create bridge br-test
      command: nmcli connection add type bridge con-name br-test ifname br-test
      when: bridge_check.rc != 0

    - name: Check interface enp7s0
      command: nmcli connection show bridge-slave-enx3c18a0d4cf8f
      register: slave_check
      failed_when: slave_check.rc != 0
      changed_when: false

    - name: Attach enp7s0 to bridge
      command: nmcli connection add type bridge-slave ifname enx3c18a0d4cf8f master br-test
      when: slave_check.rc != 0

    - name: Ensure bridge br-test uses DHCP
      command: nmcli connection modify br-test ipv4.method auto
      when: bridge_check.rc == 0

    - name: Bring up bridge br-test
      command: nmcli connection up br-test
      when: bridge_check.rc == 0

    - name: Bring up bridge br-test explicitly
      command: ip link set br-test up
      when: bridge_check.rc == 0

    - name: Restart NetworkManager
      service:
        name: NetworkManager
        state: restarted
      when: bridge_check.rc == 0

    - name: Restart systemd-networkd
      service:
        name: systemd-networkd
        state: restarted
      when: bridge_check.rc == 0

#### Creation br-test network for libvirt

    - name: Copy br-test.xml
      copy:
        src: /home/cross/Bureau/cours_N7/s9/Projet_cloud/tf-conf/br-test.xml
        dest: /home/cross/Bureau/br-test.xml
        mode: '0644'

    - name: Check br-test
      command: virsh net-info br-test
      register: net_check
      failed_when: false
      changed_when: false

    - name: Define the libvirt network br-test
      command: virsh net-define /home/cross/Bureau/br-test.xml
      when: net_check.rc != 0

    - name: Start br-test network
      command: virsh net-start br-test
      when: net_check.rc != 0

    - name: Auto start br-test
      command: virsh net-autostart br-test
      when: net_check.rc != 0
