---
- name: Install KVM and dependencies
  hosts: my_host
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install KVM and dependencies
      apt:
        name:
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - virt-manager
        state: present

    - name: Add user to libvirt and kvm groups
      command: usermod -aG libvirt,kvm {{ ansible_user }}
      args:
        warn: false