---
- name: Install KVM and dependancies on pc distant
  hosts: pc_distant
  become: true
  tasks:
#### Installation KVM
    - name: MAJ packages
      apt:
        update_cache: yes

    - name: Installation KVM et dependances
      apt:
        name:
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - virt-manager
        state: present

    - name: Ajout user dans libvirt et kvm groups
      user:
        name: cross
        groups:
          - libvirt
          - kvm
        append: true
    
    - name: Copy qemu.conf
      copy:
        src: /etc/libvirt/qemu.conf
        dest: /etc/libvirt/qemu.conf

#### Bridge creation and config

    - name: Check bridge creation
      command: nmcli connection show br-test
      register: bridge_check
      failed_when: bridge_check.rc != 0
      changed_when: false

    - name: Créer br-test
      command: nmcli connection add type bridge con-name br-test ifname br-test
      when: bridge_check.rc != 0

    - name: Check interface enp7s0
      command: nmcli connection show bridge-slave-enp7s0 
      register: slave_check
      failed_when: slave_check.rc != 0
      changed_when: false

    - name: Attach enp7s0 to bridge
      command: nmcli connection add type bridge-slave ifname enp7s0 master br-test
      when: slave_check.rc != 0

    - name: Ajout DHCP pour br-test 
      command: nmcli connection modify br-test ipv4.method auto
      when: bridge_check.rc == 0

    - name: Up connection br-test
      command: nmcli connection up br-test
      when: bridge_check.rc == 0

    - name: Up br-test
      command: ip link set br-test up
      when: bridge_check.rc == 0

    - name: Restart NetworkManager
      service:
        name: NetworkManager
        state: restarted
      when: bridge_check.rc == 0

    - name: Restart systemd-networkd
      service:
        name: systemd-networkd
        state: restarted
      when: bridge_check.rc == 0

#### Creation br-test network for libvirt

    - name: Copy br-test.xml
      copy:
        src: /home/cross/Bureau/cours_N7/s9/Projet_cloud/tf-conf/br-test.xml
        dest: /home/cross/Bureau/br-test.xml
        mode: '0644'

    - name: Check br-test
      command: virsh net-info br-test
      register: net_check
      failed_when: false
      changed_when: false

    - name: Define br-test dans libvirt  
      command: virsh net-define /home/cross/Bureau/br-test.xml
      when: net_check.rc != 0

    - name: Start br-test network
      command: virsh net-start br-test
      when: net_check.rc != 0

    - name: Auto start br-test
      command: virsh net-autostart br-test
      when: net_check.rc != 0


      