---
- name: Démarrer Spark Master
  hosts: vm_master
  vars_files:
    - variables.yml

  tasks:

    - name: Démarrer Spark Master
      shell: "/home/cross/spark-2.4.3-bin-hadoop2.7/sbin/start-all.sh"
      args:
        executable: /bin/bash
    
    - name: Créer le répertoire WordCount
      file:
        path: "/home/cross/wordcount"
        state: directory
        mode: '0755'
    
    - name: Copy wordcount 
      copy:
        src: "/home/cross/Bureau/cours_N7/s9/Projet_cloud/ansible-host-conf/spark-config/WordCount.java"
        dest: "/home/cross/wordcount/WordCount.java"
        owner: cross
        group: cross
        mode: '0644'

    - name: Compiler le WordCount
      shell: |
        /home/cross/jdk1.8.0_202/bin/javac -cp ".:/home/cross/spark-2.4.3-bin-hadoop2.7/jars/spark-core_2.11-2.4.3.jar:/home/cross/spark-2.4.3-bin-hadoop2.7/jars/scala-library-2.11.12.jar:/home/cross/hadoop-2.7.1/share/hadoop/common/hadoop-common-2.7.1.jar" WordCount.java
        /home/cross/jdk1.8.0_202/bin/jar cf wc.jar *.class
        rm *.class
      args:
        chdir: "/home/cross/wordcount"

    - name: Copy filesample dans le bin
      copy:
        src: "/home/cross/Bureau/cours_N7/s9/Projet_cloud/ansible-host-conf/spark-config/filesample.txt"
        dest: "/home/cross/spark-2.4.3-bin-hadoop2.7/bin/filesample.txt"
        owner: cross
        group: cross
        mode: '0644'
    
    - name: Copy filesample
      copy:
        src: "/home/cross/Bureau/cours_N7/s9/Projet_cloud/ansible-host-conf/spark-config/filesample.txt"
        dest: "/home/cross/wordcount/filesample.txt"
        owner: cross
        group: cross
        mode: '0644'

    - name: Lancer le jar dans le cluster spark
      shell: |
        ./spark-submit --class WordCount --master spark://{{ master_spark }}:7077 /home/cross/wordcount/wc.jar /home/cross/spark-2.4.3-bin-hadoop2.7/bin/filesample.txt
      args:
        chdir: "/home/cross/spark-2.4.3-bin-hadoop2.7/bin"


